# Generated by Django 4.2.7 on 2025-08-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiotrack",
            name="artist_name",
        ),
        migrations.AlterField(
            model_name="transformedtrack",
            name="style",
            field=models.CharField(
                choices=[
                    ("lofi", "Lo-fi"),
                    ("phonk", "Phonk"),
                    ("melody", "Melody"),
                    ("8d", "8D Audio"),
                ],
                max_length=20,
            ),
        ),
    ]
